# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39af66cb611c22ce6cb6960a085948c540524c3db1fadbc022a1b20e724c464a599916f4949af472a3f5bf6c4e73e3116779ac7a7b0530a2a9bc94ff9ac43636

test:
  secret_key_base: 8f405c8bc6b366483aa7925854094909a64ff4e3ca02170886df44d071a8bea53a4bf27e09131af9e137cd1a0759412cd53d28cd35454c5af1514cdacf6de93e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
